version: "3"

services:
  site:
    image: kisenka/jekyll
    restart: always
    tty: true
    ports:
      - 4000:4000
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      JEKYLL_ENV: development
    entrypoint: rake preview
